# Generated by Django 5.0.1 on 2024-01-28 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectpost",
            options={"verbose_name_plural": "寻亲贴收藏"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name_plural": "寻亲贴用户评论"},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name_plural": "用户反馈"},
        ),
        migrations.AlterModelOptions(
            name="forwardpost",
            options={"verbose_name": "寻亲贴转发"},
        ),
        migrations.AlterModelOptions(
            name="likepost",
            options={"verbose_name_plural": "寻亲贴点赞"},
        ),
        migrations.AlterModelOptions(
            name="missingfamilypost",
            options={"verbose_name_plural": "寻亲贴"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "User"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name_plural": "用户"},
        ),
        migrations.AlterModelOptions(
            name="volunteer",
            options={"verbose_name_plural": "志愿者申请"},
        ),
        migrations.AddField(
            model_name="missingfamilypost",
            name="verification_status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已驳回")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PostsVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="display.missingfamilypost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "寻亲贴发布审核",
            },
        ),
    ]
