# Generated by Django 5.0.1 on 2024-02-18 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0002_alter_collectpost_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "用户"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name_plural": "用户关注"},
        ),
        migrations.AlterModelOptions(
            name="verification",
            options={"verbose_name_plural": "认证-父模型"},
        ),
        migrations.AlterField(
            model_name="postsverification",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="display.missingfamilypost",
            ),
        ),
        migrations.AlterField(
            model_name="postsverification",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已驳回")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="通知信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "通知信息",
            },
        ),
    ]
