# Generated by Django 5.0.1 on 2024-02-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0003_alter_user_options_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("0", "not read"), ("1", "has been read")],
                default="0",
                max_length=20,
            ),
        ),
    ]
